### ISSUE TITLE
Can't save any results to session after promise\await

### ISSUE THREAD

**Issue by Sxela** [alexnzarov/telegraf-session-mongodb-examples#1]
For example, i have this code:
```
bot.on('text', async (ctx) => {
      ctx.session.msg0 = 'wowow'
      ctx.reply('woot').then(res=>ctx.session.msg1 = res)
      const msg = await ctx.reply('woot')
      
      ctx.session.msg2 = msg.message_id
      ctx.session.msg3 = 'wowow'
      handleRequest(ctx)
    })
```

Only msg0 is saved to the db, other 3 are accessible in this function's scope, but not afterwards.

**Comment by Sxela** [comment]
Okay, placing the middleware a second time right before the bot.on(async.. seems to solve the issue. Looks like it waits only for 1 next() before saving the data? not all of them. Still, it only works 1 level deep, updating values in a nested function inside bot.on won't work for promises

Or you can call saveSession manually

**Comment by olexnzarov** [comment]
Hey. I see several problems with this code. 

1. Middleware should be added before any other handler that needs this middleware. 

2. This package works by fetching the session object from the database and assigning it to the 'session' property of the context and then calling the 'next' function to resume the logic. After that, it awaits the result of the 'next' function and stores the updated session to the database. If something happens in that time (like an exception), it will not store the updated session object. If anything changes the session after the 'next' result is resolved, it won't be saved.

This piece of code is problematic, that promise can be resolved after the middleware saved the session and it won't be updated:

```js
ctx.reply('woot').then(res=>ctx.session.msg1 = res)
```

**Comment by Sxela** [comment]
Thanks for a fast reply :D
I've decided to call saveSession manually after async update, works fine.
